const providers=SOURCE_REGISTRY;
const carsRaw=[
{id:'d1',provider:'demo_de',key:'bmw330e',make:'BMW',model:'330e',version:'M Sport',name:'BMW 330e M Sport',year:2020,km:97000,price:18900,fuel:'Híbrido',gear:'Automático',body:'Berlina',seller:'Profesional',hp:292,co2:36,serviceHistory:'full',owners:2,accidentHistory:'none',warrantyMonths:12},
{id:'d2',provider:'demo_de',key:'audia5',make:'Audi',model:'A5 Sportback',version:'40 TDI',name:'Audi A5 Sportback 40 TDI',year:2019,km:118000,price:17950,fuel:'Diésel',gear:'Automático',body:'Berlina',seller:'Profesional',hp:190,co2:135,serviceHistory:'full',owners:2,accidentHistory:'unknown',warrantyMonths:12},
{id:'d3',provider:'demo_de',key:'merc300',make:'Mercedes-Benz',model:'C 300 Coupé',version:'',name:'Mercedes-Benz C 300 Coupé',year:2018,km:105000,price:19900,fuel:'Gasolina',gear:'Automático',body:'Coupé',seller:'Profesional',hp:245,co2:168,serviceHistory:'partial',owners:3,accidentHistory:'unknown',warrantyMonths:6},
{id:'d4',provider:'demo_de',key:'golfgti',make:'Volkswagen',model:'Golf GTI',version:'Performance',name:'Volkswagen Golf GTI Performance',year:2018,km:89000,price:17400,fuel:'Gasolina',gear:'Automático',body:'Compacto',seller:'Profesional',hp:245,co2:161,serviceHistory:'full',owners:2,accidentHistory:'none',warrantyMonths:12},
{id:'d5',provider:'demo_de',key:'xc60d4',make:'Volvo',model:'XC60',version:'D4 R-Design',name:'Volvo XC60 D4 R-Design',year:2018,km:132000,price:18600,fuel:'Diésel',gear:'Automático',body:'SUV',seller:'Profesional',hp:190,co2:149,serviceHistory:'partial',owners:3,accidentHistory:'unknown',warrantyMonths:6},
{id:'d6',provider:'demo_de',key:'leonfr',make:'SEAT',model:'León',version:'FR 1.5 TSI',name:'SEAT León FR 1.5 TSI',year:2020,km:74000,price:13900,fuel:'Gasolina',gear:'Manual',body:'Compacto',seller:'Profesional',hp:150,co2:128,serviceHistory:'full',owners:1,accidentHistory:'none',warrantyMonths:12},
{id:'d7',provider:'demo_de',key:'octavia',make:'Skoda',model:'Octavia Combi',version:'2.0 TDI',name:'Skoda Octavia Combi 2.0 TDI',year:2020,km:112000,price:14500,fuel:'Diésel',gear:'Automático',body:'Familiar',seller:'Profesional',hp:150,co2:122,serviceHistory:'full',owners:2,accidentHistory:'none',warrantyMonths:12},
{id:'d8',provider:'demo_de',key:'kona64',make:'Hyundai',model:'Kona Electric',version:'64 kWh',name:'Hyundai Kona Electric 64 kWh',year:2020,km:68000,price:15900,fuel:'Eléctrico',gear:'Automático',body:'SUV',seller:'Profesional',hp:204,co2:0,serviceHistory:'full',owners:2,accidentHistory:'none',warrantyMonths:12,batteryHealth:89}
];
const cars=carsRaw.map(x=>normalizeListing(x,x.provider));
const esComparables={
 bmw330e:[['BMW 330e M Sport',2020,101000,24200],['BMW 330e M Sport',2020,88000,24950],['BMW 330e',2019,109000,22900],['BMW 330e M Sport',2021,94000,25900],['BMW 330e',2020,116000,23500]],
 audia5:[['Audi A5 Sportback 40 TDI',2019,123000,22800],['Audi A5 Sportback 40 TDI',2020,109000,24500],['Audi A5 Sportback TDI',2019,132000,21900],['Audi A5 Sportback 40 TDI',2018,113000,22200],['Audi A5 Sportback',2020,125000,23900],['Audi A5 Sportback 40 TDI',2019,98000,24700]],
 merc300:[['Mercedes C 300 Coupé',2018,109000,25900],['Mercedes C 300 Coupé',2019,99000,27400],['Mercedes C 300 Coupé',2018,117000,25100],['Mercedes C 300 Coupé',2017,98000,24400]],
 golfgti:[['Golf GTI Performance',2018,93000,22800],['Golf GTI Performance',2019,82000,23900],['Golf GTI Performance',2018,103000,21900],['Golf GTI Performance',2017,87000,21400]],
 xc60d4:[['Volvo XC60 D4 R-Design',2018,137000,23900],['Volvo XC60 D4',2019,121000,25200],['Volvo XC60 D4 R-Design',2018,119000,24900],['Volvo XC60 D4',2017,142000,22800]],
 leonfr:[['SEAT León FR 1.5 TSI',2020,79000,17900],['SEAT León FR 1.5 TSI',2021,69000,19100],['SEAT León FR',2019,85000,16900],['SEAT León FR 1.5 TSI',2020,64000,18600]],
 octavia:[['Skoda Octavia Combi 2.0 TDI',2020,118000,18800],['Skoda Octavia Combi 2.0 TDI',2021,103000,19900],['Skoda Octavia Combi TDI',2019,126000,17600],['Skoda Octavia Combi 2.0 TDI',2020,99000,19400]],
 kona64:[['Hyundai Kona Electric 64 kWh',2020,73000,19900],['Hyundai Kona Electric 64 kWh',2021,62000,20900],['Hyundai Kona Electric',2019,81000,18400],['Hyundai Kona Electric 64 kWh',2020,59000,20500]]
};

const $=id=>document.getElementById(id);
const euro=n=>n==null||!Number.isFinite(n)?'—':Math.round(n).toLocaleString('es-ES')+' €';
function percentile(a,p){a=[...a].sort((x,y)=>x-y);const i=(a.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return l===h?a[l]:a[l]+(a[h]-a[l])*(i-l)}
function riskRank(level){return {'Bajo':1,'Medio':2,'Alto':3,'Muy alto':4}[level]||4}
function riskClass(level){return level==='Bajo'?'good':level==='Medio'?'warn':'bad'}

const VERIFY_KEY='autoimport-v14-verifications', HISTORY_KEY='autoimport-v14-history', ORDER_KEY='autoimport-v14-order', SETTINGS_KEY='autoimport-v14-settings', PROPOSAL_KEY='autoimport-v14-proposal', CRM_KEY='autoimport-v14-crm';
const RESERVATION_SETTINGS_KEY='autoimport-v15-reservation-settings', CONTRACT_KEY='autoimport-v16-contract', CONTRACT_SETTINGS_KEY='autoimport-v16-contract-settings';
let verificationOverrides={},historyReports={},lastCandidates=[],proposalState={payments:[],paymentPlan:[],sellerPayment:{}},crmRecords=[],activeRecordId='',reservationSettings={whatsapp:''},contractState={},contractSettings={providerName:'',providerTaxId:'',providerAddress:'',providerEmail:''};
try{verificationOverrides=JSON.parse(localStorage.getItem(VERIFY_KEY)||'{}')||{}}catch{}
try{historyReports=JSON.parse(localStorage.getItem(HISTORY_KEY)||'{}')||{}}catch{}
try{proposalState=JSON.parse(localStorage.getItem(PROPOSAL_KEY)||'{\"payments\":[]}')||{payments:[],paymentPlan:[]}}catch{proposalState={payments:[],paymentPlan:[]}}
try{reservationSettings=JSON.parse(localStorage.getItem(RESERVATION_SETTINGS_KEY)||'{\"whatsapp\":\"\"}')||{whatsapp:''}}catch{reservationSettings={whatsapp:''}}

function renderSources(){
  $('sourceCards').innerHTML=Object.values(providers).map(p=>`<div class="source-card"><div class="source-top"><div class="source-name">${p.name} · ${p.country}</div><span class="status-pill ${p.status==='requested'||p.status==='planned'?'pending':p.status}">${p.statusText}</span></div><div class="seller-net">${p.role}</div><div class="micro">${p.note}</div></div>`).join('');
}
function similarity(base,x){const yg=Math.abs(base.year-x.year),kg=Math.abs(base.km-x.km);return Math.max(0,Math.min(100,Math.round(100-yg*9-Math.min(28,kg/5000*2))))}
function marketFor(c){
 const raw=(esComparables[c.key]||[]).map((x,i)=>normalizeListing({id:c.key+'-'+i,key:c.key,name:x[0],make:c.make,model:c.model,year:x[1],km:x[2],price:x[3],fuel:c.fuel,gear:c.gear,body:c.body,seller:'',hp:c.hp},'demo_es'));
 const enriched=dedupeListings(raw).map(x=>({...x,match:similarity(c,x)})).filter(x=>x.match>=55).sort((a,b)=>b.match-a.match);const prices=enriched.map(x=>x.price);
 if(!prices.length)return {items:[],count:0,low:null,median:null,high:null,confidence:'Baja',avgMatch:0};
 const low=percentile(prices,.25),median=percentile(prices,.5),high=percentile(prices,.75),disp=(high-low)/median,avgMatch=enriched.reduce((a,x)=>a+x.match,0)/enriched.length;
 const confidence=enriched.length>=5&&disp<=.2?'Alta':enriched.length>=3?'Media':'Baja';return {items:enriched,count:enriched.length,low,median,high,confidence,avgMatch};
}
function getCosts(c){const r=calculateSpainImport({region:'ES_BI',purchasePrice:c.price,fiscalBase:c.price,co2:c.co2||0,sellerType:c.seller==='Particular'?'private':'professional',fiscalStatus:'used',transport:+$('cfgTransport').value||0,itv:+$('cfgItv').value||0,dgtFee:+$('cfgDgt').value||99.77,homologation:+$('cfgHomologation').value||0,plates:+$('cfgPlates').value||0,municipalTax:+$('cfgMunicipal').value||0,gestor:+$('cfgRegistration').value||0,prep:+$('cfgPrep').value||0,risk:+$('cfgRisk').value||0});return {transport:r.transport,itv:r.itv,dgt:r.dgt,homologation:r.homologation,plates:r.plates,municipal:r.municipalTax,registration:r.gestor,prep:r.prep,risk:r.risk,tax:r.registrationTax,itp:r.itp}}
function historyReportFor(c){return historyReports[c.id]||null}
function historyAssessmentFor(c){const r=historyReportFor(c);return r?assessHistoryReport(r,c):null}
function baseVerification(c){return {vin:'',registrationDocs:'unknown',ownershipProof:'unknown',technicalDocs:'unknown',roadworthiness:'unknown',serviceHistory:c?.serviceHistory||'unknown',accidentHistory:c?.accidentHistory||'unknown',independentInspection:'not_done',mileageConsistency:'unknown',sellerIdentity:'unknown',modified:'unknown'}}
function verificationFor(c){const manual=verificationOverrides[c.id]||null,history=historyReportFor(c);if(!manual&&!history)return null;const patch=history?historyToVerificationPatch(history):{};return assessPrePurchaseVerification({...baseVerification(c),...patch,...(manual||{})})}
function calcBase(c){const market=marketFor(c),costs=getCosts(c),importCost=Object.values(costs).reduce((a,b)=>a+b,0),total=c.price+importCost,verification=verificationFor(c),history=historyAssessmentFor(c),risk=assessVehicleRisk(c,market,{configuredReserve:costs.risk,currentYear:2026,verification,history}),adjustedTotal=total+risk.extraReserve;return {...c,market,costs,importCost,total,verification,history,risk,adjustedTotal}}

function currentOrder(){return normalizeOrder({client:$('orderClient').value,phone:$('orderPhone').value,email:$('orderEmail').value,reference:$('orderRef').value,query:$('orderQ').value,budget:$('orderBudget').value,minProfit:$('orderMinProfit').value,targetProfit:$('orderTargetProfit').value,operationBuffer:$('orderBuffer').value,minYear:$('minYear').value,maxKm:$('maxKm').value,fuel:$('fuel').value,gear:$('gear').value,body:$('body').value,seller:$('seller').value,maxRisk:$('maxRisk').value,equipment:$('orderEquipment').value,internalNotes:$('orderInternalNotes').value,status:$('orderStatus').value})}
function matchesOrder(c,o){const words=o.query.toLowerCase().split(/\s+/).filter(Boolean),text=(c.make+' '+c.model+' '+c.version+' '+c.name).toLowerCase();return (!words.length||words.every(w=>text.includes(w)))&&c.year>=o.minYear&&(!o.maxKm||c.km<=o.maxKm)&&(!o.fuel||c.fuel===o.fuel)&&(!o.gear||c.gear===o.gear)&&(!o.body||c.body===o.body)&&(!o.seller||c.seller===o.seller)&&riskRank(c.risk.level)<=o.maxRisk}
function maxPurchaseAllowed(c,o){
 if(!o.budget)return null;
 let lo=0,hi=o.budget;
 for(let i=0;i<36;i++){
  const p=(lo+hi)/2;
  const r=calculateSpainImport({region:'ES_BI',purchasePrice:p,fiscalBase:p,co2:c.co2||0,sellerType:c.seller==='Particular'?'private':'professional',fiscalStatus:'used',transport:+$('cfgTransport').value||0,itv:+$('cfgItv').value||0,dgtFee:+$('cfgDgt').value||99.77,homologation:+$('cfgHomologation').value||0,plates:+$('cfgPlates').value||0,municipalTax:+$('cfgMunicipal').value||0,gestor:+$('cfgRegistration').value||0,prep:+$('cfgPrep').value||0,risk:+$('cfgRisk').value||0});
  const finalNeed=r.landedCost+(c.risk?.extraReserve||0)+o.operationBuffer+o.minProfit;
  if(finalNeed<=o.budget)lo=p;else hi=p;
 }
 return lo;
}
function fitScore(c,o){let s=100-c.risk.score*.35;if(c.year>o.minYear)s+=Math.min(8,c.year-o.minYear);if(o.maxKm)s+=Math.max(0,Math.min(8,(o.maxKm-c.km)/10000));if(c.orderEconomics.status==='Viable')s+=15;else if(c.orderEconomics.status==='Viable ajustado')s+=6;else s-=25;if(c.market.confidence==='Alta')s+=5;return Math.max(0,Math.min(100,Math.round(s)))}
function orderStatusClass(s){return s==='Viable'?'good':s==='Viable ajustado'?'warn':'bad'}
function toggleComp(id){const el=$('cmp-'+id);el.style.display=el.style.display==='block'?'none':'block'} window.toggleComp=toggleComp;
function toggleRisk(id){const el=$('risk-'+id);el.style.display=el.style.display==='block'?'none':'block'} window.toggleRisk=toggleRisk;

function renderWorkflow(){const cur=$('orderStatus').value,idx=ORDER_STAGES.indexOf(cur);$('workflow').innerHTML=ORDER_STAGES.map((s,i)=>`<div class="workflow-step ${i<idx?'done':i===idx?'current':''}">${i+1}. ${s}</div>`).join('')}
function renderOrderAssessment(candidates){const o=currentOrder(),a=assessOrder(candidates,o),cls=orderLevelClass(a.level);$('orderAssessment').innerHTML=`<div class="order-kpi"><span>Estado presupuesto</span><b class="${cls}">${a.level}</b></div><div class="order-kpi"><span>Candidatos viables</span><b>${a.viable}</b></div><div class="order-kpi"><span>Mínimo final realista</span><b>${euro(a.minimumRequired)}</b></div><div class="order-kpi"><span>Objetivo final realista</span><b>${euro(a.targetRequired)}</b></div><div class="order-kpi"><span>Referencia mercado España</span><b>${euro(a.spanishMarket)}</b></div><div class="order-message"><b class="${cls}">${a.message}</b>${o.budget&&a.spanishMarket?`<p class="budget-note">Presupuesto cliente: ${euro(o.budget)} · referencia española aproximada: ${euro(a.spanishMarket)}. La viabilidad se decide por el coste real del candidato + reservas + tu beneficio, no solo por el precio medio español.</p>`:''}</div>`}
function searchCars(){
 const o=currentOrder();let out=cars.map(calcBase).map(c=>({...c,orderEconomics:candidateOrderEconomics(c,o)})).filter(c=>matchesOrder(c,o));out=out.map(c=>{const maxPurchase=maxPurchaseAllowed(c,o);return {...c,maxPurchase,purchaseHeadroom:maxPurchase==null?null:maxPurchase-c.price,fitScore:fitScore(c,o)}}).sort((a,b)=>{const rank=s=>s==='Viable'?0:s==='Viable ajustado'?1:2;return rank(a.orderEconomics.status)-rank(b.orderEconomics.status)||b.fitScore-a.fitScore||a.orderEconomics.minimumClientPrice-b.orderEconomics.minimumClientPrice});
 renderOrderAssessment(out);const viable=out.filter(c=>c.orderEconomics.status!=='No viable').length,best=out[0],minFinal=out.length?Math.min(...out.map(c=>c.orderEconomics.minimumClientPrice)):null,avgRisk=out.length?out.reduce((a,c)=>a+c.risk.score,0)/out.length:null;
 $('summary').innerHTML=`<div class="kpi"><span class="muted">Candidatos</span><b>${out.length}</b></div><div class="kpi"><span class="muted">Viables por presupuesto</span><b>${viable}</b></div><div class="kpi"><span class="muted">Mínimo final encontrado</span><b>${euro(minFinal)}</b></div><div class="kpi"><span class="muted">Mejor encaje</span><b>${best?best.fitScore+'/100':'—'}</b></div><div class="kpi"><span class="muted">Riesgo medio</span><b>${avgRisk==null?'—':avgRisk.toFixed(0)+'/100'}</b></div>`;
 $('results').innerHTML=out.map(c=>{const e=c.orderEconomics,sc=orderStatusClass(e.status),budget=o.budget;return `<article class="card result"><div><span class="fit-pill ${sc}">${e.status}</span><h2>${c.name}</h2><div class="muted">${c.year} · ${c.km.toLocaleString('es-ES')} km · ${c.hp} CV · ${c.seller}</div><p><span class="tag">${c.fuel}</span><span class="tag">${c.gear}</span><span class="tag ${riskClass(c.risk.level)}">Riesgo ${c.risk.level} · ${c.risk.score}/100</span></p><div class="source">Origen: ${providers[c.provider].name} · DEMO</div>
 <div class="order-econ"><div><span>Compra origen</span><b>${euro(c.price)}</b></div><div><span>Coste puesto en España</span><b>${euro(c.total)}</b></div><div><span>Coste ajustado + riesgo</span><b>${euro(c.adjustedTotal)}</b></div><div><span>Colchón operativo encargo</span><b>${euro(o.operationBuffer)}</b></div><div><span>Precio mínimo con tu beneficio</span><b>${euro(e.minimumClientPrice)}</b></div><div><span>Precio objetivo</span><b>${euro(e.targetClientPrice)}</b></div><div><span>Presupuesto cliente</span><b>${euro(budget)}</b></div><div><span>Margen disponible al máximo</span><b class="${e.marginAtBudget!=null&&e.marginAtBudget>=o.minProfit?'good':'bad'}">${euro(e.marginAtBudget)}</b></div><div><span>Máximo a pagar en origen</span><b>${euro(c.maxPurchase)}</b></div><div><span>Holgura compra / negociación</span><b class="${c.purchaseHeadroom!=null&&c.purchaseHeadroom>=0?'good':'bad'}">${euro(c.purchaseHeadroom)}</b></div></div>
 <button class="chooseProposal" onclick="openProposalFor('${c.id}')">Preparar propuesta al cliente</button><button class="compareToggle" onclick="openHistory('${c.id}')">Historial VIN</button><button class="compareToggle" onclick="openVerification('${c.id}')">Verificar coche</button><button class="compareToggle" onclick="toggleRisk('${c.id}')">Riesgo</button><button class="compareToggle" onclick="toggleComp('${c.id}')">Mercado España</button>
 <div class="risk-detail" id="risk-${c.id}"><b>Factores de riesgo</b>${c.risk.reasons.length?`<ul>${c.risk.reasons.map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p class="muted">Sin alertas destacadas.</p>'}<b>Factores favorables</b>${c.risk.positives.length?`<ul>${c.risk.positives.map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p class="muted">Sin datos suficientes.</p>'}</div>
 <div class="comparables" id="cmp-${c.id}"><p class="muted">Referencia española: P25 ${euro(c.market.low)} · mediana ${euro(c.market.median)} · P75 ${euro(c.market.high)} · confianza ${c.market.confidence}</p>${c.market.items.map(x=>`<div class="comp"><b>${x.name}</b><span>${x.year}</span><span>${x.km.toLocaleString('es-ES')} km</span><b>${euro(x.price)}</b><span>${x.match}/100</span></div>`).join('')}</div></div>
 <aside class="side"><div class="small">Precio recomendado al cliente</div><div class="client-price ${sc}">${e.recommendedClientPrice==null?'NO VIABLE':euro(e.recommendedClientPrice)}</div><div class="small">Beneficio protegido con ese precio</div><b>${euro(e.protectedProfit)}</b><div class="small">Beneficio mínimo configurado</div><b>${euro(o.minProfit)}</b><div class="small">Beneficio objetivo</div><b>${euro(o.targetProfit)}</b><div class="small">Holgura frente al presupuesto</div><b class="${e.minRoom!=null&&e.minRoom>=0?'good':'bad'}">${euro(e.minRoom)}</b><div class="small">Referencia mercado España</div><b>${euro(c.market.median)}</b><p class="budget-note">La app no recomienda cobrar automáticamente el máximo del cliente; propone el precio necesario para cubrir la operación y el beneficio configurado.</p></aside></article>`}).join('')||'<section class="panel"><b>No hay candidatos con estos criterios.</b><p class="muted">Prueba con otro año, kilometraje o modelo. Cuando conectemos más plataformas, este mismo encargo consultará todas las fuentes autorizadas.</p></section>';
 lastCandidates=out;refreshProposalCarOptions(out);
 saveAll();
}


function candidateForProposal(id){
 const o=currentOrder(),base=cars.find(x=>x.id===id);if(!base)return null;
 let c=calcBase(base);c={...c,orderEconomics:candidateOrderEconomics(c,o)};const maxPurchase=maxPurchaseAllowed(c,o);return {...c,maxPurchase,purchaseHeadroom:maxPurchase==null?null:maxPurchase-c.price,fitScore:fitScore(c,o)};
}
function refreshProposalCarOptions(candidates=lastCandidates){
 if(!$('proposalCar'))return;
 const cur=$('proposalCar').value||proposalState.carId||'';
 let list=candidates.length?[...candidates]:cars.map(x=>candidateForProposal(x.id)).filter(Boolean);
 if(cur&&!list.some(c=>c.id===cur)){const savedCar=candidateForProposal(cur);if(savedCar)list.unshift(savedCar)}
 $('proposalCar').innerHTML=list.map(c=>`<option value="${c.id}">${c.name} · ${c.year} · ${euro(c.orderEconomics.recommendedClientPrice)}</option>`).join('');
 if(cur&&list.some(c=>c.id===cur))$('proposalCar').value=cur;
 else if(list[0])$('proposalCar').value=list[0].id;
 if($('proposalCar').value)loadProposalIntoForm($('proposalCar').value,false);
}
function proposalRawFromForm(){
 const proof=$('sellerPayProof')?.files?.[0]?.name||proposalState?.sellerPayment?.proofName||'';
 return {carId:$('proposalCar').value,client:$('proposalClient').value,contact:$('proposalContact').value,status:$('proposalStatus').value,finalPrice:$('proposalFinalPrice').value,depositMode:$('proposalDepositMode').value,depositValue:$('proposalDepositValue').value,delivery:$('proposalDelivery').value,validity:$('proposalValidity').value,includes:$('proposalIncludes').value,notes:$('proposalNotes').value,payments:proposalState.payments||[],paymentPlan:proposalState.paymentPlan||[],sellerPayment:{seller:$('sellerPayName').value,amount:$('sellerPayAmount').value,status:$('sellerPayStatus').value,date:$('sellerPayDate').value,reference:$('sellerPayReference').value,proofName:proof}}
}
function proposalCar(){return lastCandidates.find(c=>c.id===$('proposalCar').value)||candidateForProposal($('proposalCar').value)}
function cleanWhatsAppNumber(v){return String(v||'').replace(/\D/g,'')}
function reservationWhatsAppMessage(p,c,o){
 const ref=o.reference?` (${o.reference})`:'';
 return `Hola, quiero iniciar la reserva de mi encargo${ref}.\n\nVehículo: ${c.name} ${c.year}\nPrecio final estimado: ${euro(p.finalPrice)}\nSeñal / reserva indicada: ${euro(p.depositAmount)}\nCliente: ${p.client||o.client||'—'}\n\nQuiero confirmar los pasos y la forma de realizar la reserva.`;
}
function reservationWhatsAppUrl(p,c,o){const phone=cleanWhatsAppNumber(reservationSettings.whatsapp);return phone?`https://wa.me/${phone}?text=${encodeURIComponent(reservationWhatsAppMessage(p,c,o))}`:''}
function saveReservationWhatsApp(){const input=$('reservationWhatsApp');if(!input)return;reservationSettings.whatsapp=cleanWhatsAppNumber(input.value);localStorage.setItem(RESERVATION_SETTINGS_KEY,JSON.stringify(reservationSettings));input.value=reservationSettings.whatsapp;renderProposal();renderWhatsAppStatus()}
function renderWhatsAppStatus(){const el=$('whatsappStatus');if(!el)return;const phone=cleanWhatsAppNumber(reservationSettings.whatsapp);el.innerHTML=phone?`WhatsApp configurado: <b>+${phone}</b> · El botón de reserva ya puede abrir la conversación.`:'Configura tu número con prefijo internacional (España: 34) para activar la reserva por WhatsApp.'}
function openReservationWhatsApp(){const c=proposalCar();if(!c)return;const p=normalizeProposal(proposalRawFromForm(),c,currentOrder());if(!isCurrentContractAccepted()){alert('Antes de iniciar la reserva, el contrato vigente debe estar aceptado.');document.getElementById('contractPanel')?.scrollIntoView({behavior:'smooth'});return}const url=reservationWhatsAppUrl(p,c,currentOrder());if(!url){alert('Configura primero tu WhatsApp de reservas. Ejemplo para España: 34600111222');$('reservationWhatsApp')?.focus();return}window.open(url,'_blank','noopener')}
function clientProposalMarkup(p,c,o){
 const paidRows=p.payments.length?p.payments.map(x=>`<div class="cp-box"><span>${x.date} · ${x.concept}</span><b>${euro(x.amount)}</b><small>${x.method||''}</small></div>`).join(''):'<div class="cp-box"><span>Pagos a intermediación</span><b>Aún no registrados</b></div>';
 const waUrl=reservationWhatsAppUrl(p,c,o);
 const contractOk=isCurrentContractAccepted(); const reserveBlock=contractOk&&waUrl?`<div class="cp-section cp-reserve"><h3>Iniciar reserva</h3><p>Contrato aceptado. El pago online está temporalmente inhabilitado; continúa por WhatsApp para coordinar la señal.</p><a class="wa-reserve" href="${waUrl}" target="_blank" rel="noopener">Reservar por WhatsApp · ${euro(p.depositAmount)}</a><small>La señal no se cobra automáticamente desde esta versión de la app.</small></div>`:contractOk?`<div class="cp-section cp-reserve"><h3>Iniciar reserva</h3><p>Contrato aceptado. Falta configurar el WhatsApp de reservas.</p></div>`:`<div class="cp-section cp-reserve"><h3>Contrato pendiente</h3><p>La reserva se habilitará cuando el contrato vigente esté aceptado.</p></div>`;
 return `<div class="cp-head"><div><div class="cp-muted">${o.reference?`Encargo ${o.reference}`:'Propuesta de vehículo por encargo'}</div><h2>Propuesta para ${p.client||'cliente'}</h2>${p.contact?`<div class="cp-muted">${p.contact}</div>`:''}</div><div class="cp-badge">${p.status}</div></div><div class="cp-vehicle">${c.name}</div><div>${c.year} · ${c.km.toLocaleString('es-ES')} km · ${c.hp} CV · ${c.fuel} · ${c.gear}</div><div class="cp-grid"><div class="cp-box"><span>Precio total estimado</span><div class="cp-price">${euro(p.finalPrice)}</div></div><div class="cp-box"><span>Vehículo · pago directo vendedor</span><b>${euro(p.sellerPayment.amount)}</b><small>${p.sellerPayment.status}</small></div><div class="cp-box"><span>Señal / reserva</span><b>${euro(p.depositAmount)}</b></div><div class="cp-box"><span>Pagado a intermediación</span><b>${euro(p.paid)}</b></div><div class="cp-box"><span>Pagado identificado total</span><b>${euro(p.operationPaid)}</b></div><div class="cp-box"><span>Pendiente estimado operación</span><b>${euro(p.balance)}</b></div></div><div class="direct-pay-notice"><b>Forma de compra:</b> el cliente paga el vehículo directamente al vendedor. Ese importe no es un cobro de la intermediación.</div>${reserveBlock}<div class="cp-section"><h3>Vehículo y encargo</h3><p>${o.equipment?`Condiciones solicitadas: ${o.equipment}. `:''}La unidad definitiva queda sujeta a disponibilidad y verificación.</p></div><div class="cp-section"><h3>Qué incluye</h3><p>${p.includes}</p></div><div class="cp-section"><h3>Entrega y validez</h3><p><b>Entrega:</b> ${p.delivery}<br><b>Validez:</b> ${p.validity}</p></div><div class="cp-section"><h3>Pagos registrados a intermediación</h3><div class="cp-grid">${paidRows}</div></div><div class="cp-section"><h3>Notas</h3><p>${p.notes}</p></div><p class="cp-muted">El precio final puede requerir confirmación si cambian la unidad elegida, impuestos, documentación, transporte u otros costes externos antes de formalizar la operación.</p>`;
}

function contractRawFromForm(){
 return {
  id:contractState.id||'',providerName:$('contractProviderName')?.value||'',providerTaxId:$('contractProviderTaxId')?.value||'',providerAddress:$('contractProviderAddress')?.value||'',providerEmail:$('contractProviderEmail')?.value||'',
  clientName:$('contractClientName')?.value||'',clientId:$('contractClientId')?.value||'',clientAddress:$('contractClientAddress')?.value||'',scope:$('contractScope')?.value||'',directPaymentClause:$('contractDirectPayment')?.value||'',estimateClause:$('contractEstimateClause')?.value||'',availabilityClause:$('contractAvailabilityClause')?.value||'',cancellationTerms:$('contractCancellation')?.value||'',extraTerms:$('contractExtraTerms')?.value||'',signerName:$('contractSignerName')?.value||'',
  checks:{scope:!!$('contractCheckScope')?.checked,directPayment:!!$('contractCheckDirect')?.checked,estimates:!!$('contractCheckEstimate')?.checked,cancellation:!!$('contractCheckCancellation')?.checked},
  acceptedAt:contractState.acceptedAt||'',acceptanceId:contractState.acceptanceId||'',acceptedFingerprint:contractState.acceptedFingerprint||''
 }
}
function currentContract(){
 const c=proposalCar(),o=currentOrder(),p=c?normalizeProposal(proposalRawFromForm(),c,o):{};
 return normalizeContract(contractRawFromForm(),p,o,c,contractSettings)
}
function isCurrentContractAccepted(){try{return !!currentContract().accepted}catch{return false}}
function contractDate(iso){if(!iso)return '—';try{return new Intl.DateTimeFormat('es-ES',{dateStyle:'medium',timeStyle:'short'}).format(new Date(iso))}catch{return iso}}
function contractText(c){
 const eur=n=>Math.round(+n||0).toLocaleString('es-ES')+' €';
 return `CONTRATO / ENCARGO DE INTERMEDIACIÓN PARA BÚSQUEDA DE VEHÍCULO\n\nIntermediario: ${c.providerName||'—'}\nNIF/CIF: ${c.providerTaxId||'—'}\nDomicilio: ${c.providerAddress||'—'}\nEmail: ${c.providerEmail||'—'}\n\nCliente: ${c.clientName||'—'}\nDocumento: ${c.clientId||'—'}\nDomicilio: ${c.clientAddress||'—'}\nReferencia: ${c.reference||'—'}\n\nEncargo: ${c.vehicleRequest||'—'}\nUnidad propuesta: ${c.selectedVehicle||'—'}\nPresupuesto máximo indicado: ${eur(c.maxBudget)}\nPrecio total estimado de la propuesta: ${eur(c.proposalPrice)}\nPago directo estimado al vendedor: ${eur(c.sellerDirectAmount)}\nReserva prevista: ${eur(c.depositAmount)}\n\n1. OBJETO DEL ENCARGO\n${c.scope}\n\n2. PAGO DEL VEHÍCULO\n${c.directPaymentClause}\n\n3. COSTES Y ESTIMACIONES\n${c.estimateClause}\n\n4. DISPONIBILIDAD\n${c.availabilityClause}\n\n5. CANCELACIÓN Y RESERVA\n${c.cancellationTerms||'[Pendiente de completar]'}\n${c.extraTerms?`\n6. CONDICIONES ADICIONALES\n${c.extraTerms}`:''}\n\nAceptación: ${c.accepted?'ACEPTADO':'NO ACEPTADO'}\nFirmante: ${c.signerName||'—'}\nFecha: ${contractDate(c.acceptedAt)}\nReferencia de aceptación: ${c.acceptanceId||'—'}\n\nNOTA INTERNA DE PRELANZAMIENTO: plantilla operativa pendiente de revisión jurídica antes de su uso comercial.`;
}
function contractDocumentMarkup(c){
 const eur=n=>Math.round(+n||0).toLocaleString('es-ES')+' €';
 return `<div class="contract-document"><div class="draft-mark">PLANTILLA OPERATIVA · pendiente de revisión jurídica antes de uso comercial</div><h1>Contrato / encargo de intermediación para búsqueda de vehículo</h1><div class="meta">Referencia: ${c.reference||'—'} · Estado: ${c.accepted?'Aceptado':'Borrador'}</div><div class="contract-summary"><div><b>Intermediario</b><br>${c.providerName||'—'}<br>${c.providerTaxId||'—'}<br>${c.providerAddress||'—'}<br>${c.providerEmail||''}</div><div><b>Cliente</b><br>${c.clientName||'—'}<br>${c.clientId||'—'}<br>${c.clientAddress||'—'}</div><div><b>Encargo</b><br>${c.vehicleRequest||'—'}<br>${c.selectedVehicle||'Unidad por determinar'}</div><div><b>Resumen económico</b><br>Presupuesto máximo: ${eur(c.maxBudget)}<br>Propuesta estimada: ${eur(c.proposalPrice)}<br>Pago directo vendedor: ${eur(c.sellerDirectAmount)}<br>Reserva: ${eur(c.depositAmount)}</div></div><h2>1. Objeto del encargo</h2><p>${c.scope}</p><h2>2. Pago del vehículo</h2><p>${c.directPaymentClause}</p><h2>3. Costes y estimaciones</h2><p>${c.estimateClause}</p><h2>4. Disponibilidad</h2><p>${c.availabilityClause}</p><h2>5. Cancelación y reserva</h2><p>${c.cancellationTerms||'<b>Pendiente de completar.</b>'}</p>${c.extraTerms?`<h2>6. Condiciones adicionales</h2><p>${c.extraTerms}</p>`:''}<div class="accept-box"><b>Aceptación</b><p>Firmante: ${c.signerName||'—'}<br>Estado: ${c.accepted?'ACEPTADO':'NO ACEPTADO'}<br>Fecha: ${contractDate(c.acceptedAt)}<br>Referencia: ${c.acceptanceId||'—'}</p></div></div>`
}
function saveContract(persistRecord=true){
 const c=currentContract();contractState=c;
 contractSettings={providerName:c.providerName,providerTaxId:c.providerTaxId,providerAddress:c.providerAddress,providerEmail:c.providerEmail};
 localStorage.setItem(CONTRACT_KEY,JSON.stringify(contractState));localStorage.setItem(CONTRACT_SETTINGS_KEY,JSON.stringify(contractSettings));
 if(persistRecord&&activeRecordId)saveOrderRecord(false);renderContractPanel();renderProposal();
}
function loadContractIntoForm(raw={}){
 const car=proposalCar(),o=currentOrder(),p=car?normalizeProposal(proposalRawFromForm(),car,o):{},c=normalizeContract(raw,p,o,car,contractSettings);contractState=c;
 const vals={contractProviderName:c.providerName,contractProviderTaxId:c.providerTaxId,contractProviderAddress:c.providerAddress,contractProviderEmail:c.providerEmail,contractClientName:c.clientName,contractClientId:c.clientId,contractClientAddress:c.clientAddress,contractScope:c.scope,contractDirectPayment:c.directPaymentClause,contractEstimateClause:c.estimateClause,contractAvailabilityClause:c.availabilityClause,contractCancellation:c.cancellationTerms,contractExtraTerms:c.extraTerms,contractSignerName:c.signerName};
 Object.entries(vals).forEach(([id,v])=>{if($(id))$(id).value=v||''});
 if($('contractCheckScope'))$('contractCheckScope').checked=!!c.checks.scope;if($('contractCheckDirect'))$('contractCheckDirect').checked=!!c.checks.directPayment;if($('contractCheckEstimate'))$('contractCheckEstimate').checked=!!c.checks.estimates;if($('contractCheckCancellation'))$('contractCheckCancellation').checked=!!c.checks.cancellation;
 renderContractPanel();
}
function renderContractPanel(){
 if(!$('contractPanel'))return;const car=proposalCar(),o=currentOrder(),p=car?normalizeProposal(proposalRawFromForm(),car,o):{},e=car?proposalEconomics(p,car,o):null,c=normalizeContract(contractRawFromForm(),p,o,car,contractSettings),r=contractReadiness(c,e),status=contractStatus(c,r.ready);
 const pill=$('contractStatusPill');pill.textContent=status;pill.className='status-pill '+(c.accepted?'live':c.changedAfterAcceptance?'bad':r.ready?'pending':'demo');
 $('contractEconomics').innerHTML=`<div class="contract-kpi"><span>Precio propuesta</span><b>${euro(c.proposalPrice)}</b></div><div class="contract-kpi"><span>Pago directo vendedor</span><b>${euro(c.sellerDirectAmount)}</b></div><div class="contract-kpi"><span>Reserva prevista</span><b>${euro(c.depositAmount)}</b></div><div class="contract-kpi"><span>Referencia</span><b>${c.reference||'—'}</b></div>`;
 const msgs=[];if(c.changedAfterAcceptance)msgs.push('<b class="bad">El contrato cambió después de su aceptación. Debe aceptarse de nuevo antes de reservar.</b>');if(r.missing.length)msgs.push(`<b>Falta completar:</b><ul>${r.missing.map(x=>`<li>${x}</li>`).join('')}</ul>`);if(!r.allChecks)msgs.push('<span class="muted">Para aceptar, el cliente debe marcar las cuatro declaraciones.</span>');if(!r.signerOk)msgs.push('<span class="muted">Falta el nombre completo del firmante.</span>');if(c.accepted)msgs.push(`<b class="good">Aceptado el ${contractDate(c.acceptedAt)} · ${c.acceptanceId}</b>`);
 $('contractReadiness').innerHTML=`<div class="box">${msgs.join('')||'<b class="good">Contrato listo para aceptar.</b>'}</div>`;
 $('acceptContractBtn').disabled=!r.canAccept||c.accepted;$('reservationWhatsAppBtn').disabled=!c.accepted;
 $('contractPrint').innerHTML=contractDocumentMarkup(c);
 return {contract:c,readiness:r};
}
function initContract(){
 loadContractIntoForm(contractState||{});
 ['contractProviderName','contractProviderTaxId','contractProviderAddress','contractProviderEmail','contractClientName','contractClientId','contractClientAddress','contractScope','contractDirectPayment','contractEstimateClause','contractAvailabilityClause','contractCancellation','contractExtraTerms','contractSignerName','contractCheckScope','contractCheckDirect','contractCheckEstimate','contractCheckCancellation'].forEach(id=>$(id)?.addEventListener('input',renderContractPanel));
 $('saveContract').addEventListener('click',()=>saveContract(true));
 $('acceptContractBtn').addEventListener('click',()=>{const x=renderContractPanel();if(!x?.readiness.canAccept)return;contractState=acceptContract(x.contract);contractSettings={providerName:contractState.providerName,providerTaxId:contractState.providerTaxId,providerAddress:contractState.providerAddress,providerEmail:contractState.providerEmail};localStorage.setItem(CONTRACT_KEY,JSON.stringify(contractState));localStorage.setItem(CONTRACT_SETTINGS_KEY,JSON.stringify(contractSettings));if(activeRecordId)saveOrderRecord(false);loadContractIntoForm(contractState);renderProposal()});
 $('resetContractAcceptance').addEventListener('click',()=>{contractState=revokeContractAcceptance(currentContract());localStorage.setItem(CONTRACT_KEY,JSON.stringify(contractState));if(activeRecordId)saveOrderRecord(false);loadContractIntoForm(contractState);renderProposal()});
 $('copyContract').addEventListener('click',async()=>{const txt=contractText(currentContract());try{await navigator.clipboard.writeText(txt);$('copyContract').textContent='Copiado ✓';setTimeout(()=>$('copyContract').textContent='Copiar contrato',1200)}catch{const ta=document.createElement('textarea');ta.value=txt;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}});
 $('printContract').addEventListener('click',()=>{renderContractPanel();document.body.classList.add('print-contract');window.print();setTimeout(()=>document.body.classList.remove('print-contract'),300)});
}

function renderPayments(p,e){
 if(!p.paymentPlan?.length)p.paymentPlan=buildAutomaticPaymentPlan(p,e);
 proposalState.paymentPlan=p.paymentPlan;
 const sum=paymentSummary(p.paymentPlan,p.payments);
 const sellerPaid=p.sellerPaid||0;
 $('paymentDashboard').innerHTML=`<div class="proposal-kpi"><span>Debes cobrar tú</span><b>${euro(sum.expected)}</b></div><div class="proposal-kpi"><span>Recibido por ti</span><b class="${sum.received+0.01>=sum.expected?'good':'warn'}">${euro(sum.received)}</b></div><div class="proposal-kpi"><span>Pendiente contigo</span><b>${euro(sum.pending)}</b></div><div class="proposal-kpi"><span>Vehículo · pago externo</span><b>${euro(p.sellerPayment.amount)}</b></div><div class="proposal-kpi"><span>Vehículo pagado</span><b class="${sellerPaid?'good':'warn'}">${euro(sellerPaid)}</b></div>`;
 const current=$('paymentCharge').value;
 $('paymentCharge').innerHTML=sum.rows.map(r=>`<option value="${r.id}">${r.concept} · pendiente ${euro(r.remaining)}</option>`).join('');
 if(current&&sum.rows.some(r=>r.id===current))$('paymentCharge').value=current;
 $('paymentSchedule').innerHTML=`<div class="payment-plan-table"><div class="payment-plan-head"><span>Concepto</span><span>Previsto</span><span>Recibido</span><span>Pendiente</span><span>Estado</span></div>${sum.rows.map(r=>`<div class="payment-plan-row"><span><b>${r.concept}</b><small>${r.type}</small></span><span>${euro(r.expected)}</span><span>${euro(r.paid)}</span><span>${euro(r.remaining)}</span><span class="${r.status==='Pagado'?'good':r.status==='Parcial'?'warn':''}">${r.status}</span></div>`).join('')||'<p class="muted">Crea el plan automático de cobros.</p>'}</div>`;
 $('paymentList').innerHTML=p.payments.map((x,i)=>`<div class="payment-row v15-row"><span>${x.date}</span><b>${x.concept}</b><span>${euro(x.amount)}</span><span>${x.method||'Transferencia bancaria'}</span><small>${x.reference||'Sin referencia'}</small><button class="secondary" onclick="printPaymentReceipt(${i})">Recibo</button><button onclick="removePayment(${i})">Eliminar</button></div>`).join('')||'<p class="muted">Todavía no hay cobros registrados.</p>';
}
function renderProposal(){
 if(!$('proposalCar'))return;const c=proposalCar(),o=currentOrder();if(!c){$('proposalInternal').innerHTML='<div class="proposal-warning warn">Selecciona un candidato para preparar la propuesta.</div>';$('clientProposal').innerHTML='';return}
 const p=normalizeProposal(proposalRawFromForm(),c,o),e=proposalEconomics(p,c,o);if(!p.paymentPlan?.length)p.paymentPlan=buildAutomaticPaymentPlan(p,e);proposalState={...p,payments:p.payments,paymentPlan:p.paymentPlan,sellerPayment:p.sellerPayment};
 $('paymentAmount').placeholder=Math.round(Math.max(0,p.depositAmount-p.paid));
 $('sellerPaymentSummary').innerHTML=`<div class="proposal-internal"><div class="proposal-kpi"><span>Importe vehículo</span><b>${euro(p.sellerPayment.amount)}</b></div><div class="proposal-kpi"><span>Estado</span><b>${p.sellerPayment.status}</b></div><div class="proposal-kpi"><span>Pagado directamente</span><b class="${p.sellerPaid?'good':'warn'}">${euro(p.sellerPaid)}</b></div><div class="proposal-kpi"><span>Recibido por ti</span><b>0 € de este pago</b></div>${p.sellerPayment.proofName?`<div class="proposal-kpi"><span>Justificante</span><b>${p.sellerPayment.proofName}</b></div>`:''}</div>`;
 $('proposalInternal').innerHTML=`<div class="proposal-kpi"><span>Compra vehículo · cliente→vendedor</span><b>${euro(c.price)}</b></div><div class="proposal-kpi"><span>Costes/riesgo estimados</span><b>${euro(e.thirdPartyCosts)}</b></div><div class="proposal-kpi"><span>Coste interno operación</span><b>${euro(e.operational)}</b></div><div class="proposal-kpi"><span>Precio final</span><b>${euro(p.finalPrice)}</b></div><div class="proposal-kpi"><span>Tu margen estimado</span><b class="${e.meetsMin?'good':'bad'}">${euro(e.profit)}</b></div><div class="proposal-kpi"><span>Beneficio mínimo</span><b>${euro(o.minProfit)}</b></div><div class="proposal-kpi"><span>Dentro presupuesto</span><b class="${e.withinBudget?'good':'warn'}">${e.withinBudget?'Sí':'No'}</b></div>${e.warnings.length?`<div class="proposal-warning bad"><b>No lista para enviar</b><ul>${e.warnings.map(x=>`<li>${x}</li>`).join('')}</ul></div>`:`<div class="proposal-warning good"><b>Propuesta rentable:</b> protege el beneficio mínimo configurado.</div>`}`;
 renderPayments(p,e);$('clientProposal').innerHTML=clientProposalMarkup(p,c,o);renderWhatsAppStatus();renderContractPanel();
}
function loadProposalIntoForm(id,forceDefaults=true){
 const c=candidateForProposal(id);if(!c)return;const o=currentOrder();let saved=proposalState&&proposalState.carId===id?proposalState:{};if(forceDefaults&&proposalState.carId!==id)saved={payments:[],paymentPlan:[]};const p=normalizeProposal(saved,c,o);proposalState={...p,payments:p.payments,paymentPlan:p.paymentPlan};
 $('proposalCar').value=id;$('proposalClient').value=p.client||o.client||'';$('proposalContact').value=p.contact||o.phone||o.email||'';$('proposalStatus').value=p.status;$('proposalFinalPrice').value=Math.round(p.finalPrice);$('proposalDepositMode').value=p.depositMode;$('proposalDepositValue').value=p.depositValue;$('proposalDelivery').value=p.delivery;$('proposalValidity').value=p.validity;$('proposalIncludes').value=p.includes;$('proposalNotes').value=p.notes;$('sellerPayName').value=p.sellerPayment.seller||'';$('sellerPayAmount').value=Math.round(p.sellerPayment.amount||c.price);$('sellerPayStatus').value=p.sellerPayment.status;$('sellerPayDate').value=p.sellerPayment.date||'';$('sellerPayReference').value=p.sellerPayment.reference||'';renderProposal();
}
function saveProposal(){const c=proposalCar();if(!c)return;const p=normalizeProposal(proposalRawFromForm(),c,currentOrder());proposalState={...p,paymentPlan:proposalState.paymentPlan||p.paymentPlan||[],updatedAt:new Date().toISOString()};localStorage.setItem(PROPOSAL_KEY,JSON.stringify(proposalState));renderProposal();if(activeRecordId)saveOrderRecord(false)}
function openProposalFor(id){const exists=[...$('proposalCar').options].some(o=>o.value===id);if(!exists){const c=candidateForProposal(id);if(c)$('proposalCar').insertAdjacentHTML('beforeend',`<option value="${c.id}">${c.name} · ${c.year}</option>`)}loadProposalIntoForm(id,true);document.querySelector('.proposal-panel').scrollIntoView({behavior:'smooth'})} window.openProposalFor=openProposalFor;
function removePayment(i){proposalState.payments=(proposalState.payments||[]).filter((_,n)=>n!==i);saveProposal()} window.removePayment=removePayment;
function addPayment(amount,chargeId,date,method,reference){amount=+amount||0;if(amount<=0)return;const c=proposalCar();if(!c)return;const p=normalizeProposal(proposalRawFromForm(),c,currentOrder()),e=proposalEconomics(p,c,currentOrder());if(!proposalState.paymentPlan?.length)proposalState.paymentPlan=buildAutomaticPaymentPlan(p,e);const charge=(proposalState.paymentPlan||[]).find(x=>x.id===chargeId);proposalState.payments=proposalState.payments||[];proposalState.payments.push(normalizeReceipt({chargeId:chargeId||'',amount,concept:charge?.concept||'Pago',date,method,reference}));saveProposal()}
function printPaymentReceipt(i){const p=proposalState.payments?.[i],c=proposalCar(),o=currentOrder();if(!p||!c)return;const w=window.open('','_blank','width=700,height=850');if(!w)return;w.document.write(`<html><head><title>Recibo ${p.id||''}</title><style>body{font-family:Arial,sans-serif;padding:40px;color:#111}h1{font-size:24px}.box{border:1px solid #ccc;padding:16px;margin:18px 0}.amt{font-size:28px;font-weight:700}</style></head><body><h1>Recibo de pago</h1><p>Encargo: <b>${o.reference||'—'}</b></p><p>Cliente: <b>${o.client||p.client||'—'}</b></p><div class="box"><p>${p.concept}</p><div class="amt">${euro(p.amount)}</div><p>Fecha: ${p.date}</p><p>Método: ${p.method||'—'}</p><p>Referencia: ${p.reference||'—'}</p></div><p>Vehículo: ${c.name}</p><p>Este recibo registra un cobro de la intermediación. El precio del vehículo se abona directamente al vendedor y no forma parte de este recibo.</p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()} window.printPaymentReceipt=printPaymentReceipt;
function initProposal(){
 $('proposalStatus').innerHTML=PROPOSAL_STATUSES.map(x=>`<option>${x}</option>`).join('');$('sellerPayStatus').innerHTML=SELLER_PAYMENT_STATUSES.map(x=>`<option>${x}</option>`).join('');$('paymentDate').value=new Date().toISOString().slice(0,10);$('sellerPayDate').value='';$('reservationWhatsApp').value=reservationSettings.whatsapp||'';renderWhatsAppStatus();$('proposalIncludes').value='Búsqueda y selección del vehículo; verificación; coordinación de compra; transporte a España; trámites de importación, ITV y matriculación según presupuesto; seguimiento del encargo.';$('proposalNotes').value='El vehículo se paga directamente al vendedor por el cliente. La reserva inicial se coordina por WhatsApp mientras el pago online permanezca inhabilitado. La propuesta queda sujeta a disponibilidad, verificación documental/mecánica y confirmación de costes.';
 ['proposalClient','proposalContact','proposalStatus','proposalFinalPrice','proposalDepositMode','proposalDepositValue','proposalValidity','proposalDelivery','proposalIncludes','proposalNotes','sellerPayName','sellerPayAmount','sellerPayStatus','sellerPayDate','sellerPayReference'].forEach(id=>$(id).addEventListener('input',renderProposal));$('proposalCar').addEventListener('change',()=>loadProposalIntoForm($('proposalCar').value,true));
 $('saveProposal').addEventListener('click',saveProposal);$('saveSellerPayment').addEventListener('click',saveProposal);$('saveReservationWhatsApp').addEventListener('click',saveReservationWhatsApp);$('reservationWhatsAppBtn').addEventListener('click',openReservationWhatsApp);$('reservationWhatsApp').addEventListener('change',saveReservationWhatsApp);$('acceptProposal').addEventListener('click',()=>{$('proposalStatus').value='Aceptada';$('orderStatus').value='Cliente aprueba';renderWorkflow();saveAll();saveProposal()});
 $('buildPaymentPlan').addEventListener('click',()=>{const c=proposalCar();if(!c)return;const p=normalizeProposal(proposalRawFromForm(),c,currentOrder()),e=proposalEconomics(p,c,currentOrder());proposalState.paymentPlan=buildAutomaticPaymentPlan(p,e);saveProposal()});
 $('addPayment').addEventListener('click',()=>{addPayment($('paymentAmount').value,$('paymentCharge').value,$('paymentDate').value,$('paymentMethod').value,$('paymentReference').value);$('paymentAmount').value='';$('paymentReference').value='' });
 $('registerDeposit').addEventListener('click',()=>{const c=proposalCar();if(!c)return;const p=normalizeProposal(proposalRawFromForm(),c,currentOrder()),e=proposalEconomics(p,c,currentOrder());if(!proposalState.paymentPlan?.length)proposalState.paymentPlan=buildAutomaticPaymentPlan(p,e);const dep=proposalState.paymentPlan.find(x=>x.id==='auto-deposit')||proposalState.paymentPlan[0];if(!dep)return;const sum=paymentSummary(proposalState.paymentPlan,p.payments),row=sum.rows.find(x=>x.id===dep.id),missing=row?.remaining||0;if(missing>0)addPayment(missing,dep.id,$('paymentDate').value,$('paymentMethod').value||'Transferencia bancaria',$('paymentReference').value||'Reserva coordinada manualmente');$('proposalStatus').value='Señal pagada';saveProposal()});
 $('copyProposal').addEventListener('click',async()=>{const c=proposalCar();if(!c)return;const p=normalizeProposal(proposalRawFromForm(),c,currentOrder()),txt=proposalClientText(p,c,currentOrder());try{await navigator.clipboard.writeText(txt);$('copyProposal').textContent='Copiado ✓';setTimeout(()=>$('copyProposal').textContent='Copiar texto cliente',1200)}catch{const ta=document.createElement('textarea');ta.value=txt;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}});$('printProposal').addEventListener('click',()=>{document.body.classList.remove('print-contract');window.print()});
}

function renderHistoryProviders(){if(!$('historyProviders'))return;$('historyProviders').innerHTML=Object.entries(HISTORY_PROVIDERS).map(([id,p])=>`<div class="history-provider-card"><div class="top"><b>${p.name}</b><span class="status-pill ${p.status==='demo'?'demo':'pending'}">${p.statusText}</span></div><p>${p.note}</p></div>`).join('')}
function historyClass(v){if(v.blockers?.length||v.score<55)return 'bad';if(v.score<88)return 'warn';return 'good'}
function renderHistoryResult(car,report){if(!report){$('historyResult').innerHTML='<div class="history-detail"><b>Sin informe guardado</b><p class="muted">Introduce un VIN y usa el modo DEMO para probar el flujo.</p></div>';return}const h=assessHistoryReport(report,car),cls=historyClass(h);$('historyResult').innerHTML=`<div class="history-kpi"><span>Puntuación</span><b class="${cls}">${h.score}/100</b></div><div class="history-kpi"><span>Proveedor</span><b>${HISTORY_PROVIDERS[report.provider]?.name||report.provider}</b></div><div class="history-kpi"><span>Reserva adicional</span><b>${euro(h.extraReserve)}</b></div><div class="history-kpi"><span>Decisión</span><div class="history-decision ${cls}">${h.decision}</div></div><div class="history-detail"><b>VIN</b><p>${report.vin||'—'}</p>${h.blockers.length?`<b>Bloqueos</b><ul>${h.blockers.map(x=>`<li class="bad">${x}</li>`).join('')}</ul>`:''}${h.warnings.length?`<b>Advertencias</b><ul>${h.warnings.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}</div>`}
function initHistory(){renderHistoryProviders();$('historyCar').innerHTML=cars.map(c=>`<option value="${c.id}">${c.name} · ${c.year}</option>`).join('');const load=()=>{const c=cars.find(x=>x.id===$('historyCar').value)||cars[0],r=historyReportFor(c);$('historyVin').value=r?.vin||verificationOverrides[c.id]?.vin||'';renderHistoryResult(c,r)};$('historyCar').addEventListener('change',load);$('runHistoryDemo').addEventListener('click',()=>{const c=cars.find(x=>x.id===$('historyCar').value)||cars[0],vin=$('historyVin').value.trim().toUpperCase();if(!vinLooksValid(vin)){$('historyResult').innerHTML='<div class="history-detail bad"><b>VIN no válido.</b></div>';return}historyReports[c.id]=deterministicDemoHistory(c,vin);localStorage.setItem(HISTORY_KEY,JSON.stringify(historyReports));load();searchCars()});$('clearHistory').addEventListener('click',()=>{delete historyReports[$('historyCar').value];localStorage.setItem(HISTORY_KEY,JSON.stringify(historyReports));load();searchCars()});load()}
function openHistory(id){$('historyCar').value=id;const c=cars.find(x=>x.id===id)||cars[0],r=historyReportFor(c);$('historyVin').value=r?.vin||verificationOverrides[id]?.vin||'';renderHistoryResult(c,r);document.querySelector('.history-panel').scrollIntoView({behavior:'smooth'})} window.openHistory=openHistory;

function collectVerificationForm(){return {vin:$('verifyVin').value.trim().toUpperCase(),registrationDocs:$('verifyRegistration').value,ownershipProof:$('verifyOwnership').value,technicalDocs:$('verifyTechnical').value,roadworthiness:$('verifyRoadworthiness').value,serviceHistory:$('verifyService').value,accidentHistory:$('verifyAccident').value,independentInspection:$('verifyInspection').value,mileageConsistency:$('verifyMileage').value,sellerIdentity:$('verifySeller').value,modified:$('verifyModified').value}}
function setVerificationForm(d){$('verifyVin').value=d.vin||'';$('verifyRegistration').value=d.registrationDocs||'unknown';$('verifyOwnership').value=d.ownershipProof||'unknown';$('verifyTechnical').value=d.technicalDocs||'unknown';$('verifyRoadworthiness').value=d.roadworthiness||'unknown';$('verifyService').value=d.serviceHistory||'unknown';$('verifyAccident').value=d.accidentHistory||'unknown';$('verifyInspection').value=d.independentInspection||'not_done';$('verifyMileage').value=d.mileageConsistency||'unknown';$('verifySeller').value=d.sellerIdentity||'unknown';$('verifyModified').value=d.modified||'unknown'}
function renderVerificationPreview(saved=false){const v=assessPrePurchaseVerification(collectVerificationForm()),cls=v.blockers?.length||v.score<55?'bad':v.score<88?'warn':'good';$('verificationResult').innerHTML=`<div class="verify-kpi"><span>Puntuación</span><b class="${cls}">${v.score}/100</b></div><div class="verify-kpi"><span>Calidad</span><b>${v.level}</b></div><div class="verify-kpi"><span>Reserva extra</span><b>${euro(v.extraReserve)}</b></div><div class="verify-kpi"><span>Decisión</span><div class="verify-decision ${cls}">${v.decision}</div></div><div class="verify-detail">${v.blockers.length?`<b>Bloqueos</b><ul>${v.blockers.map(x=>`<li class="bad">${x}</li>`).join('')}</ul>`:''}${v.warnings.length?`<b>Advertencias</b><ul>${v.warnings.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}${saved?'<p class="good"><b>Guardado y aplicado al encargo.</b></p>':''}</div>`}
function loadVerificationForm(id){const c=cars.find(x=>x.id===id)||cars[0];setVerificationForm({...baseVerification(c),...(verificationOverrides[c.id]||{})});renderVerificationPreview(Boolean(verificationOverrides[c.id]))}
function initVerification(){$('verifyCar').innerHTML=cars.map(c=>`<option value="${c.id}">${c.name} · ${c.year}</option>`).join('');loadVerificationForm($('verifyCar').value);$('verifyCar').addEventListener('change',()=>loadVerificationForm($('verifyCar').value));['verifyVin','verifyRegistration','verifyOwnership','verifyTechnical','verifyRoadworthiness','verifyService','verifyAccident','verifyInspection','verifyMileage','verifySeller','verifyModified'].forEach(id=>$(id).addEventListener('input',()=>renderVerificationPreview(false)));$('saveVerification').addEventListener('click',()=>{verificationOverrides[$('verifyCar').value]=collectVerificationForm();localStorage.setItem(VERIFY_KEY,JSON.stringify(verificationOverrides));renderVerificationPreview(true);searchCars()});$('clearVerification').addEventListener('click',()=>{delete verificationOverrides[$('verifyCar').value];localStorage.setItem(VERIFY_KEY,JSON.stringify(verificationOverrides));loadVerificationForm($('verifyCar').value);searchCars()})}
function openVerification(id){$('verifyCar').value=id;loadVerificationForm(id);document.querySelector('.verify-panel').scrollIntoView({behavior:'smooth'})} window.openVerification=openVerification;

function renderTaxCalculator(){const r=calculateSpainImport({region:$('taxRegion').value,purchasePrice:+$('taxPurchase').value||0,fiscalBase:+$('taxBase').value||0,co2:+$('taxCo2').value||0,sellerType:$('taxSeller').value,fiscalStatus:$('taxStatus').value,transport:+$('cfgTransport').value||0,itv:+$('cfgItv').value||0,dgtFee:+$('cfgDgt').value||99.77,homologation:+$('cfgHomologation').value||0,plates:+$('cfgPlates').value||0,municipalTax:+$('cfgMunicipal').value||0,gestor:+$('cfgRegistration').value||0,prep:+$('cfgPrep').value||0,risk:+$('cfgRisk').value||0});$('taxResult').innerHTML=`<div class="tax-kpi"><span>IEDMT</span><b>${(r.band.rate*100).toFixed(2).replace('.',',')}%</b></div><div class="tax-kpi"><span>Impuesto matriculación</span><b>${euro(r.registrationTax)}</b></div><div class="tax-kpi"><span>ITP</span><b>${euro(r.itp)}</b></div><div class="tax-kpi"><span>DGT</span><b>${euro(r.dgt)}</b></div><div class="tax-kpi"><span>Extras</span><b>${euro(r.totalExtras)}</b></div><div class="tax-kpi"><span>Puesto en España</span><b>${euro(r.landedCost)}</b></div>${r.needsNewVehicleVatReview?'<div class="tax-alert">Revisar IVA intracomunitario.</div>':''}`}
function resetCosts(){$('cfgTransport').value=750;$('cfgItv').value=180;$('cfgDgt').value=99.77;$('cfgHomologation').value=100;$('cfgPlates').value=30;$('cfgMunicipal').value=120;$('cfgRegistration').value=150;$('cfgPrep').value=550;$('cfgRisk').value=500;searchCars();renderTaxCalculator()}
function saveAll(){const order=currentOrder();localStorage.setItem(ORDER_KEY,JSON.stringify(order));const ids=['cfgTransport','cfgItv','cfgDgt','cfgHomologation','cfgPlates','cfgMunicipal','cfgRegistration','cfgPrep','cfgRisk'];const s={};ids.forEach(id=>s[id]=$(id).value);localStorage.setItem(SETTINGS_KEY,JSON.stringify(s))}
function loadSaved(){try{const o=JSON.parse(localStorage.getItem(ORDER_KEY)||'{}');applyOrderToForm(o)}catch{}try{const s=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');Object.entries(s).forEach(([id,v])=>{if($(id))$(id).value=v})}catch{}}


function applyOrderToForm(o={}){
 const map={client:'orderClient',phone:'orderPhone',email:'orderEmail',reference:'orderRef',query:'orderQ',budget:'orderBudget',minProfit:'orderMinProfit',targetProfit:'orderTargetProfit',operationBuffer:'orderBuffer',minYear:'minYear',maxKm:'maxKm',fuel:'fuel',gear:'gear',body:'body',seller:'seller',maxRisk:'maxRisk',equipment:'orderEquipment',internalNotes:'orderInternalNotes',status:'orderStatus'};
 Object.entries(map).forEach(([k,id])=>{if(o[k]!==undefined&&$(id))$(id).value=o[k]});
}
function crmStatusClass(s){return s==='Entregado'?'good':s==='Compra'||s==='Transporte'||s==='ITV / matriculación'?'warn':''}
function persistCrm(){localStorage.setItem(CRM_KEY,JSON.stringify(crmRecords))}
function renderCrm(){
 const sum=crmSummary(crmRecords);$('crmSummary').innerHTML=`<div class="kpi"><span class="muted">Encargos</span><b>${sum.total}</b></div><div class="kpi"><span class="muted">Activos</span><b>${sum.active}</b></div><div class="kpi"><span class="muted">Buscando/opciones</span><b>${sum.searching}</b></div><div class="kpi"><span class="muted">Pago pendiente</span><b>${sum.paymentPending}</b></div><div class="kpi"><span class="muted">Entregados</span><b>${sum.delivered}</b></div>`;
 const q=($('crmSearch')?.value||'').toLowerCase().trim();const list=crmRecords.filter(r=>!q||`${r.order?.client||''} ${r.order?.reference||''} ${r.order?.query||''}`.toLowerCase().includes(q)).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));
 $('crmList').innerHTML=list.map(r=>{const o=r.order||{},p=r.proposal||{};return `<div class="crm-row ${r.id===activeRecordId?'active':''}"><div><b>${o.client||'Cliente sin nombre'}</b><span>${o.reference||'Sin referencia'} · ${o.query||'Sin vehículo'}</span></div><div><span>Presupuesto</span><b>${euro(+o.budget||0)}</b></div><div><span>Estado</span><b class="${crmStatusClass(o.status)}">${o.status||'Encargo recibido'}</b></div><div><span>Propuesta</span><b>${p.status||'Sin propuesta'}</b></div><div class="crm-actions"><button onclick="loadOrderRecord('${r.id}')">Abrir</button><button class="secondary" onclick="deleteOrderRecord('${r.id}')">Eliminar</button></div></div>`}).join('')||'<p class="muted">Todavía no hay encargos guardados.</p>';
}
function saveOrderRecord(showFeedback=true){
 const c=proposalCar();if(c)proposalState=normalizeProposal(proposalRawFromForm(),c,currentOrder());
 if($('contractPanel')){contractState=currentContract();contractSettings={providerName:contractState.providerName,providerTaxId:contractState.providerTaxId,providerAddress:contractState.providerAddress,providerEmail:contractState.providerEmail};localStorage.setItem(CONTRACT_KEY,JSON.stringify(contractState));localStorage.setItem(CONTRACT_SETTINGS_KEY,JSON.stringify(contractSettings));}
 const rec=normalizeCrmRecord({id:activeRecordId||undefined,createdAt:crmRecords.find(x=>x.id===activeRecordId)?.createdAt,order:currentOrder(),proposal:proposalState,contract:contractState,selectedCarId:proposalState.carId||''});
 activeRecordId=rec.id;const i=crmRecords.findIndex(x=>x.id===rec.id);if(i>=0)crmRecords[i]=rec;else crmRecords.push(rec);persistCrm();localStorage.setItem('autoimport-v18-active-record',rec.id);saveAll();renderCrm();
 const flash=(label='Guardado ✓')=>{
   if(!showFeedback)return;
   const topBtn=$('saveOrderRecord'),formBtn=$('saveOrder');
   if(topBtn)topBtn.textContent=label;
   if(formBtn)formBtn.textContent=label;
   setTimeout(()=>{if(topBtn)topBtn.textContent='Guardar / actualizar ficha';if(formBtn)formBtn.textContent='Guardar encargo'},1400);
 };
 flash();
 if(window.AutoImportCloud?.enabled){
   window.AutoImportCloud.syncCrmRecord(rec).then(()=>{
     const e=$('cloudSyncStatus');if(e){e.textContent='Encargo guardado local + nube ✓';e.className='micro good'}
   }).catch(err=>{
     const e=$('cloudSyncStatus');if(e){e.textContent='Guardado local; nube: '+err.message;e.className='micro warn'}
     if(showFeedback){const formBtn=$('saveOrder');if(formBtn)formBtn.textContent='Guardado local ✓'}
   })
 }
 return rec;
}
function loadOrderRecord(id){
 const r=crmRecords.find(x=>x.id===id);if(!r)return;activeRecordId=id;localStorage.setItem('autoimport-v18-active-record',id);applyOrderToForm(r.order||{});proposalState=r.proposal||{payments:[],paymentPlan:[],sellerPayment:{}};contractState=r.contract||{};localStorage.setItem(PROPOSAL_KEY,JSON.stringify(proposalState));localStorage.setItem(CONTRACT_KEY,JSON.stringify(contractState));renderWorkflow();searchCars();loadContractIntoForm(contractState);renderCrm();window.scrollTo({top:0,behavior:'smooth'});
}
window.loadOrderRecord=loadOrderRecord;
function deleteOrderRecord(id){crmRecords=crmRecords.filter(x=>x.id!==id);if(activeRecordId===id){activeRecordId='';localStorage.removeItem('autoimport-v18-active-record')}persistCrm();renderCrm();if(window.AutoImportCloud?.enabled)window.AutoImportCloud.deleteWorkspaceRecord(id).catch(()=>{})}
window.deleteOrderRecord=deleteOrderRecord;
function newOrderRecord(){
 activeRecordId='';proposalState={payments:[],paymentPlan:[],sellerPayment:{}};contractState={};localStorage.setItem(CONTRACT_KEY,'{}');applyOrderToForm({client:'',phone:'',email:'',reference:'',query:'Audi A5',budget:25000,minProfit:1500,targetProfit:2500,operationBuffer:400,minYear:2018,maxKm:140000,fuel:'',gear:'',body:'',seller:'',maxRisk:2,equipment:'',internalNotes:'',status:ORDER_STAGES[0]});localStorage.setItem(PROPOSAL_KEY,JSON.stringify(proposalState));renderWorkflow();searchCars();loadContractIntoForm(contractState);renderCrm();
 const panel=document.querySelector('.order-panel');if(panel)panel.scrollIntoView({behavior:'smooth',block:'start'});
 setTimeout(()=>{$('orderClient')?.focus()},450);
}
document.addEventListener('DOMContentLoaded',()=>{
 $('orderStatus').innerHTML=ORDER_STAGES.map(s=>`<option>${s}</option>`).join('');loadSaved();renderWorkflow();renderSources();initHistory();initVerification();initProposal();initContract();renderCrm();
 $('analyzeOrder').addEventListener('click',searchCars);$('saveOrder').addEventListener('click',()=>{saveOrderRecord();searchCars()});$('saveOrderRecord').addEventListener('click',()=>saveOrderRecord());$('newOrderRecord').addEventListener('click',newOrderRecord);$('crmSearch').addEventListener('input',renderCrm);$('orderStatus').addEventListener('change',()=>{renderWorkflow();saveAll()});
 ['orderClient','orderPhone','orderEmail','orderQ','orderBudget','orderMinProfit','orderTargetProfit','orderBuffer','minYear','maxKm','fuel','gear','body','seller','maxRisk','orderEquipment','orderInternalNotes'].forEach(id=>$(id).addEventListener('change',searchCars));
 $('resetCosts').addEventListener('click',resetCosts);['cfgTransport','cfgItv','cfgDgt','cfgHomologation','cfgPlates','cfgMunicipal','cfgRegistration','cfgPrep','cfgRisk'].forEach(id=>$(id).addEventListener('change',()=>{searchCars();renderTaxCalculator()}));
 ['taxPurchase','taxBase','taxCo2','taxSeller','taxStatus','taxRegion'].forEach(id=>$(id).addEventListener('input',renderTaxCalculator));renderTaxCalculator();searchCars();
});
